name: Ejecutar colección Postman (CSV completo)

on:
  workflow_dispatch:
  schedule:
    - cron: '08 8 * * *'    # 08:08 UTC (05:08 ART) diario

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3           # clon mínimo

      - name: Instalar Newman
        run: |
          npm install -g newman@6 newman-reporter-csv@1
          newman --version

      - name: Ejecutar colección y generar CSV completo
        run: |
          mkdir -p reports
          newman run "Generar Tokens.postman_collection.json" \
            -e "YPF-LW PROD.postman_environment.json" \
            --env-var client_id=${{ secrets.LOCATION_CLIENT_ID }} \
            --env-var client_secret=${{ secrets.LOCATION_CLIENT_SECRET }} \
            --env-var audience=${{ secrets.LOCATION_AUDIENCE }} \
            -r cli,csv \
            --reporter-csv-includeBody \
            --reporter-csv-export reports/resultados-completos.csv \
            --suppress-exit-code

      - name: Subir artefacto
        uses: actions/upload-artifact@v4
        with:
          name: resultados-completos
          path: reports/resultados-completos.csv
