name: Ejecutar colección Postman (CSV completo)

on:
  workflow_dispatch:
  schedule:
    - cron: '08 8 * * *'      # 08:08 UTC (05:08 ART) todos los días

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      # 1) Clonar el repo (historial mínimo basta porque no haremos push)
      - uses: actions/checkout@v3

      # 2) Instalar Newman y reporter CSV
      - name: Instalar Newman
        run: |
          npm install -g newman@6 newman-reporter-csv@1
          newman --version

      # 3) Ejecutar la colección y exportar un CSV con CUERPOS incluidos
      - name: Ejecutar colección y generar CSV completo
        run: |
          mkdir -p reports
          newman run "Generar Tokens.postman_collection.json" \
            -e "YPF-LW PROD.postman_environment.json" \
            --env-var client_id=${{ secrets.LOCATION_CLIENT_ID }} \
            --env-var client_secret=${{ secrets.LOCATION_CLIENT_SECRET }} \
            --env-var audience=${{ secrets.LOCATION_AUDIENCE }} \
            -r cli,csv \
            --reporter-csv-includeBody \
            --reporter-csv-export reports/resultados-completos.csv \
            --suppress-exit-code   # nunca corta el flujo por códigos ≠0

      # 4) Subir el CSV completo como artefacto
      - name: Subir artefacto
        uses: actions/upload-artifact@v4
        with:
          name: resultados-completos
          path: reports/resultados-completos.csv
              git push origin HEAD:main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
