name: Ejecutar colección Postman

#  Permisos de escritura para poder hacer push
permissions:
  contents: write

on:
  workflow_dispatch:
  schedule:
    - cron: '08 8 * * *'   # 08:08 UTC (05:08 ART) todos los días

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      # ── 1. Checkout con historial completo ────────────────────────
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0          # descarga todos los commits

      # ── 2. Ejecutar Newman y generar CSV ──────────────────────────
      - name: Instalar y ejecutar Newman
        run: |
          npm install -g newman@6 newman-reporter-csv@1
          newman --version
          mkdir -p reports
          newman run "Generar Tokens.postman_collection.json" \
            -e "YPF-LW PROD.postman_environment.json" \
            --env-var client_id=${{ secrets.LOCATION_CLIENT_ID }} \
            --env-var client_secret=${{ secrets.LOCATION_CLIENT_SECRET }} \
            --env-var audience=${{ secrets.LOCATION_AUDIENCE }} \
            -r cli,csv \
            --reporter-csv-export reports/resultados.csv \
            --suppress-exit-code

      # (opcional) Diagnóstico rápido
      - name: Ver qué escribió Newman
        run: find reports -type f -name '*.csv' -print

      # ── 3. Subir artefacto para descarga manual ────────────────────
      - name: Subir resultados como artefacto
        uses: actions/upload-artifact@v4
        with:
          name: resultados-postman
          path: reports/resultados.csv

      # ── 4. Commit + push del CSV a la rama main ───────────────────
      - name: Publicar CSV en la rama main
        run: |
          git config --global user.email "bot@users.noreply.github.com"
          git config --global user.name  "bot"

          # integra último commit remoto (evita non-fast-forward)
          git pull --rebase --autostash

          git add reports/resultados.csv
          git commit -m "bot: CSV diario actualizado" || echo "Sin cambios"

          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
