name: Ejecutar colección Postman

on:
  schedule:
    - cron:  '0 8 * * *'    # Todos los días a las 08:00 UTC
  workflow_dispatch:       # Permite lanzamiento manual

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Instalar Newman y CSV reporter
        run: |
          npm install -g newman newman-reporter-csv

      - name: Ejecutar colección y exportar CSV
        run: |
          newman run "Generar Tokens.postman_collection.json" \
            -e "YPF-LW PROD.postman_environment.json" \
            -r cli,csv \
            --reporter-csv-export resultados.csv

      - name: Subir resultados como artefacto
        uses: actions/upload-artifact@v4
        with:
          name: resultados-postman
          path: resultados.csv
