name: Ejecutar colección Postman

on:
  schedule:
    - cron: '08 8 * * *'
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Instalar y ejecutar Newman
        run: |
          npm install -g newman newman-reporter-csv
          which newman
          newman --version
          newman -h | grep csv          # confirma que el reporter aparece
          echo '--- verificando archivos ---'
          ls -l "Generar Tokens.postman_collection.json" || echo "Colección NO encontrada"
          ls -l "YPF-LW PROD.postman_environment.json"   || echo "Ambiente NO encontrado"
          echo '-----------------------------'
          mkdir -p reports
          newman run "Generar Tokens.postman_collection.json" \
            -e "YPF-LW PROD.postman_environment.json" \
            --env-var client_id=${{ secrets.LOCATION_CLIENT_ID }} \
            --env-var client_secret=${{ secrets.LOCATION_CLIENT_SECRET }} \
            --env-var audience=${{ secrets.LOCATION_AUDIENCE }} \
            -r cli,csv \
            --reporter-csv-export reports/resultados.csv || true

      # NUEVO ── Muestra dónde quedó cualquier CSV
      - name: Localizar CSV generado
        run: |
          echo '--- .csv encontrados ---'
          find . -maxdepth 3 -name '*.csv' -print

      # NUEVO ── Sube todo lo que haya dentro de reports/
      - name: Subir resultados como artefacto
        uses: actions/upload-artifact@v4
        with:
          name: resultados-postman
          path: reports/*.csv
