name: Ejecutar colección Postman

on:
  schedule:
    - cron:  '0 8 * * *'    # Todos los días a las 08:00 UTC
  workflow_dispatch:       # Permite lanzamiento manual

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - name: Set Auth0 & YPF vars
        run: |
    echo "LOCATION_CLIENT_ID=${{ secrets.LOCATION_CLIENT_ID }}" >> $GITHUB_ENV
    echo "LOCATION_CLIENT_SECRET=${{ secrets.LOCATION_CLIENT_SECRET }}" >> $GITHUB_ENV
    echo "LOCATION_AUDIENCE=${{ secrets.LOCATION_AUDIENCE }}" >> $GITHUB_ENV
    echo "YPF_CLIENT_ID=${{ secrets.YPF_CLIENT_ID }}" >> $GITHUB_ENV
    echo "YPF_CLIENT_SECRET=${{ secrets.YPF_CLIENT_SECRET }}" >> $GITHUB_ENV

      - uses: actions/checkout@v3

      - name: Instalar Newman y CSV reporter
        run: |
          npm install -g newman newman-reporter-csv

      - name: Ejecutar colección y exportar CSV
        run: |
          newman run "Generar Tokens.postman_collection.json" \
            -e "YPF-LW PROD.postman_environment.json" \
            --reporters cli,csv \
            --reporter-csv-export resultados.csv

      - name: Subir resultados como artefacto
        uses: actions/upload-artifact@v4
        with:
          name: resultados-postman
          path: resultados.csv
