name: Ejecutar colección Postman

permissions:
  contents: write          # el bot puede hacer push

on:
  workflow_dispatch:
  schedule:
    - cron: '08 8 * * *'   # 08:08 UTC (05:08 ART) diario

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      # 1) Checkout con todo el historial
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0            # necesario para reset

      # 2) Ejecutar Newman y crear CSV
      - name: Instalar y ejecutar Newman
        run: |
          npm install -g newman@6 newman-reporter-csv@1
          mkdir -p reports
          newman run "Generar Tokens.postman_collection.json" \
            -e "YPF-LW PROD.postman_environment.json" \
            --env-var client_id=${{ secrets.LOCATION_CLIENT_ID }} \
            --env-var client_secret=${{ secrets.LOCATION_CLIENT_SECRET }} \
            --env-var audience=${{ secrets.LOCATION_AUDIENCE }} \
            -r cli,csv \
            --reporter-csv-export reports/resultados.csv \
            --suppress-exit-code

      # 3) Subir artefacto (opcional)
      - uses: actions/upload-artifact@v4
        with:
          name: resultados-postman
          path: reports/resultados.csv

      - name: Publicar CSV en la rama main
        run: |
          git config --global user.email "bot@users.noreply.github.com"
          git config --global user.name  "bot"

          # 1️⃣ Trae la punta remota y alinea HEAD ahí
          git fetch origin main
          git reset --soft origin/main      # <─ sin esto seguirá chocando

          # 2️⃣ Añade el CSV solo si cambió
          git add reports/resultados.csv
          git diff --cached --quiet && echo "Sin cambios" && exit 0

          # 3️⃣ Commit y push (ya es fast-forward)
          git commit -m "bot: CSV diario $(date +%F)"
          git push origin HEAD:main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
