name: Ejecutar colección Postman

on:
  schedule:
    - cron: '08 8 * * *'          # Todos los días 08:08 UTC
  workflow_dispatch:              # Permite lanzarlo manualmente

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Instalar y ejecutar Newman
        run: |
          npm install -g newman newman-reporter-csv
          which newman
          newman --version
          echo '----- Verificando archivos -----'
          ls -l "Generar Tokens.postman_collection.json" || echo "Colección no encontrada"
          ls -l "YPF-LW PROD.postman_environment.json"   || echo "Ambiente no encontrado"
          echo '--------------------------------'
          newman run "Generar Tokens.postman_collection.json" \
            -e "YPF-LW PROD.postman_environment.json" \
            --env-var client_id=${{ secrets.LOCATION_CLIENT_ID }} \
            --env-var client_secret=${{ secrets.LOCATION_CLIENT_SECRET }} \
            --env-var audience=${{ secrets.LOCATION_AUDIENCE }} \
            -r cli,csv \
            --reporter-csv-export resultados.csv || true


      - name: Subir resultados como artefacto
        uses: actions/upload-artifact@v4
        with:
          name: resultados-postman
          path: resultados.csv

